#!/bin/bash

#This line must be at the top of the script in order for this to work
. ../gcode-music.sh
#Overrides to the source file above should be specified here
TEMPO=720 #Make the music play back faster

$START
$G2 $THREE_EIGHTHS 
$C3 $THREE_EIGHTHS
$E3 $THREE_EIGHTHS
$G3 $THREE_EIGHTHS
$C4 $THREE_EIGHTHS
$E4 $THREE_EIGHTHS
$G4 $WHOLE
$E4 $WHOLE
$G2SHARP $THREE_EIGHTHS
$C3 $THREE_EIGHTHS
$D3SHARP $THREE_EIGHTHS
$G3SHARP $THEE_EIGHTHS
$C4 $THREE_EIGHTHS
$D4SHARP $THREE_EIGHTHS
$G4SHARP $WHOLE
$D4SHARP $WHOLE
$A2SHARP $THREE_EIGHTHS
$D3 $THREE_EIGHTHS
$F3 $THREE_EIGHTHS
$A3SHARP $THREE_EIGHTHS
$D4 $THREE_EIGHTHS
$F4 $THREE_EIGHTHS
$A4SHARP $WHOLE
$A4SHARP $THREE_EIGHTHS
$A4SHARP $THREE_EIGHTHS
$A4SHARP $THREE_EIGHTHS
$C5 $WHOLE
$STOP
