#!/bin/bash

#This line must be at the top of the script in order for this to work
. ../gcode-music.sh
#Overrides to the source file above should be specified here
TEMPO=720 #Make the music play back faster

$START
$G2 $THREE_EIGTHS 
$C3 $THREE_EIGTHS
$E3 $THREE_EIGTHS
$G3 $THREE_EIGTHS
$C4 $THREE_EIGTHS
$E4 $THREE_EIGTHS
$G4 $WHOLE
$E4 $WHOLE
$G2SHARP $THREE_EIGTHS
$C3 $THREE_EIGTHS
$D3SHARP $THREE_EIGTHS
$G3SHARP $THEE_EIGTHS
$C4 $THREE_EIGTHS
$D4SHARP $THREE_EIGTHS
$G4SHARP $WHOLE
$D4SHARP $WHOLE
$A2SHARP $THREE_EIGTHS
$D3 $THREE_EIGTHS
$F3 $THREE_EIGTHS
$A3SHARP $THREE_EIGTHS
$D4 $THREE_EIGTHS
$F4 $THREE_EIGTHS
$A4SHARP $WHOLE
$A4SHARP $THREE_EIGTHS
$A4SHARP $THREE_EIGTHS
$A4SHARP $THREE_EIGTHS
$C5 $WHOLE
$STOP
